# Generated by Django 3.2.2 on 2021-05-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month',
        ),
    ]
